/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_CamPayload_H_
#define	_CamPayload_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleCamPayload.h"
#include "RsuCamPayload.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CamPayload_PR {
	CamPayload_PR_NOTHING,	/* No components present */
	CamPayload_PR_vehicleCamPayload,
	CamPayload_PR_rsuCamPayload
} CamPayload_PR;

/* CamPayload */
typedef struct CamPayload {
	CamPayload_PR present;
	union CamPayload_u {
		VehicleCamPayload_t	 vehicleCamPayload;
		RsuCamPayload_t	 rsuCamPayload;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamPayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamPayload;

#ifdef __cplusplus
}
#endif

#endif	/* _CamPayload_H_ */
