/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include <asn_internal.h>

#include "CamPayload.h"

static asn_TYPE_member_t asn_MBR_CamPayload_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CamPayload, choice.vehicleCamPayload),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleCamPayload,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleCamPayload"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CamPayload, choice.rsuCamPayload),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RsuCamPayload,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rsuCamPayload"
		},
};
static asn_TYPE_tag2member_t asn_MAP_CamPayload_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicleCamPayload at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rsuCamPayload at 27 */
};
static asn_CHOICE_specifics_t asn_SPC_CamPayload_specs_1 = {
	sizeof(struct CamPayload),
	offsetof(struct CamPayload, _asn_ctx),
	offsetof(struct CamPayload, present),
	sizeof(((struct CamPayload *)0)->present),
	asn_MAP_CamPayload_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CamPayload = {
	"CamPayload",
	"CamPayload",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CamPayload_1,
	2,	/* Elements count */
	&asn_SPC_CamPayload_specs_1	/* Additional specs */
};

