/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_IncompleteCovarianceMatrix_H_
#define	_IncompleteCovarianceMatrix_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IncompleteCovarianceMatrix */
typedef struct IncompleteCovarianceMatrix {
	long	 ab;
	long	 ac;
	long	 ad;
	long	 af;
	long	 bc;
	long	 bd;
	long	 bf;
	long	 cc;
	long	 cd;
	long	 cf;
	long	 dd;
	long	 df;
	long	 ff;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IncompleteCovarianceMatrix_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IncompleteCovarianceMatrix;

#ifdef __cplusplus
}
#endif

#endif	/* _IncompleteCovarianceMatrix_H_ */
