/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_LatitudePosition_H_
#define	_LatitudePosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LatitudePosition */
typedef long	 LatitudePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LatitudePosition;
asn_struct_free_f LatitudePosition_free;
asn_struct_print_f LatitudePosition_print;
asn_constr_check_f LatitudePosition_constraint;
ber_type_decoder_f LatitudePosition_decode_ber;
der_type_encoder_f LatitudePosition_encode_der;
xer_type_decoder_f LatitudePosition_decode_xer;
xer_type_encoder_f LatitudePosition_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LatitudePosition_H_ */
