/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_LongitudinalAcceleration_H_
#define	_LongitudinalAcceleration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LongitudinalAcceleration */
typedef long	 LongitudinalAcceleration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalAcceleration;
asn_struct_free_f LongitudinalAcceleration_free;
asn_struct_print_f LongitudinalAcceleration_print;
asn_constr_check_f LongitudinalAcceleration_constraint;
ber_type_decoder_f LongitudinalAcceleration_decode_ber;
der_type_encoder_f LongitudinalAcceleration_encode_der;
xer_type_decoder_f LongitudinalAcceleration_decode_xer;
xer_type_encoder_f LongitudinalAcceleration_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudinalAcceleration_H_ */
