/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_LongitudePosition_H_
#define	_LongitudePosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LongitudePosition */
typedef long	 LongitudePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LongitudePosition;
asn_struct_free_f LongitudePosition_free;
asn_struct_print_f LongitudePosition_print;
asn_constr_check_f LongitudePosition_constraint;
ber_type_decoder_f LongitudePosition_decode_ber;
der_type_encoder_f LongitudePosition_encode_der;
xer_type_decoder_f LongitudePosition_decode_xer;
xer_type_encoder_f LongitudePosition_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudePosition_H_ */
