/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_Position2D_H_
#define	_Position2D_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LongitudePosition.h"
#include "LatitudePosition.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Position2D */
typedef struct Position2D {
	LongitudePosition_t	 long2D;
	LatitudePosition_t	 lat2D;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Position2D_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Position2D;

#ifdef __cplusplus
}
#endif

#endif	/* _Position2D_H_ */
