/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_PositionCovariance_H_
#define	_PositionCovariance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionCovariance */
typedef long	 PositionCovariance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionCovariance;
asn_struct_free_f PositionCovariance_free;
asn_struct_print_f PositionCovariance_print;
asn_constr_check_f PositionCovariance_constraint;
ber_type_decoder_f PositionCovariance_decode_ber;
der_type_encoder_f PositionCovariance_encode_der;
xer_type_decoder_f PositionCovariance_decode_xer;
xer_type_encoder_f PositionCovariance_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionCovariance_H_ */
