/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_SpeedModule_H_
#define	_SpeedModule_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpeedModule */
typedef long	 SpeedModule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedModule;
asn_struct_free_f SpeedModule_free;
asn_struct_print_f SpeedModule_print;
asn_constr_check_f SpeedModule_constraint;
ber_type_decoder_f SpeedModule_decode_ber;
der_type_encoder_f SpeedModule_encode_der;
xer_type_decoder_f SpeedModule_decode_xer;
xer_type_encoder_f SpeedModule_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedModule_H_ */
