/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_Timestamp_H_
#define	_Timestamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Timestamp */
typedef struct Timestamp {
	unsigned long	 seconds;
	long	 milliseconds;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Timestamp_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_seconds_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Timestamp;

#ifdef __cplusplus
}
#endif

#endif	/* _Timestamp_H_ */
