/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_VehicleType_H_
#define	_VehicleType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleDescription.h"
#include "VehicleAttribute.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleType */
typedef struct VehicleType {
	VehicleDescription_t	 vehicleDescription;
	VehicleAttribute_t	 vehicleAttribute;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleType;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleType_H_ */
