/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_ByteString_H_
#define	_ByteString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ByteString */
typedef OCTET_STRING_t	 ByteString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ByteString;
asn_struct_free_f ByteString_free;
asn_struct_print_f ByteString_print;
asn_constr_check_f ByteString_constraint;
ber_type_decoder_f ByteString_decode_ber;
der_type_encoder_f ByteString_encode_der;
xer_type_decoder_f ByteString_decode_xer;
xer_type_encoder_f ByteString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ByteString_H_ */
