/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_CloseReply_H_
#define	_CloseReply_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CloseReply */
typedef struct CloseReply {
	long	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CloseReply_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CloseReply;

#ifdef __cplusplus
}
#endif

#endif	/* _CloseReply_H_ */
