/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_MsgReply_H_
#define	_MsgReply_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UrlString.h"
#include "ByteString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MsgReply */
typedef struct MsgReply {
	UrlString_t	 url;
	ByteString_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MsgReply_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgReply;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgReply_H_ */
