/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_OpenReply_H_
#define	_OpenReply_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UrlString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OpenReply */
typedef struct OpenReply {
	UrlString_t	 url;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OpenReply_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpenReply;

#ifdef __cplusplus
}
#endif

#endif	/* _OpenReply_H_ */
