/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_RequestMessage_H_
#define	_RequestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "OpenRequest.h"
#include "EmptyRequest.h"
#include "SendRequest.h"
#include "PublishRequest.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestMessage__payload_PR {
	RequestMessage__payload_PR_NOTHING,	/* No components present */
	RequestMessage__payload_PR_open,
	RequestMessage__payload_PR_close,
	RequestMessage__payload_PR_send,
	RequestMessage__payload_PR_publish,
	RequestMessage__payload_PR_unpublish,
	RequestMessage__payload_PR_monitor,
	RequestMessage__payload_PR_unmonitor
} RequestMessage__payload_PR;

/* RequestMessage */
typedef struct RequestMessage {
	long	 serial;
	struct RequestMessage__payload {
		RequestMessage__payload_PR present;
		union RequestMessage__payload_u {
			OpenRequest_t	 open;
			EmptyRequest_t	 close;
			SendRequest_t	 send;
			PublishRequest_t	 publish;
			EmptyRequest_t	 unpublish;
			EmptyRequest_t	 monitor;
			EmptyRequest_t	 unmonitor;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestMessage_H_ */
