/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_CamHeader_H_
#define	_CamHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "NodeID.h"
#include "NodeType.h"
#include "Timestamp.h"
#include "Position2D.h"
#include "PositionVariance.h"
#include "SpeedModule.h"
#include "Heading.h"
#include "Priority.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CamHeader */
typedef struct CamHeader {
	long	 sequenceNumber;
	NodeID_t	 nodeID;
	NodeType_t	 nodeType;
	Timestamp_t	 timestamp;
	Position2D_t	 position;
	PositionVariance_t	 positionVariance;
	SpeedModule_t	 nodeSpeed;
	Heading_t	 nodeHeading;
	Priority_t	 priority;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _CamHeader_H_ */
