/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_NearestRsu_H_
#define	_NearestRsu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Position2D;

/* NearestRsu */
typedef struct NearestRsu {
	A_SEQUENCE_OF(struct Position2D) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NearestRsu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NearestRsu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Position2D.h"

#endif	/* _NearestRsu_H_ */
