/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_NodeType_H_
#define	_NodeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeType {
	NodeType_reserved	= 0,
	NodeType_vehicle	= 1,
	NodeType_rsu	= 2
} e_NodeType;

/* NodeType */
typedef long	 NodeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeType;
asn_struct_free_f NodeType_free;
asn_struct_print_f NodeType_print;
asn_constr_check_f NodeType_constraint;
ber_type_decoder_f NodeType_decode_ber;
der_type_encoder_f NodeType_encode_der;
xer_type_decoder_f NodeType_decode_xer;
xer_type_encoder_f NodeType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeType_H_ */
