/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include <asn_internal.h>

#include "PositionVariance.h"

static int
memb_aa_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_bb_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_PositionVariance_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PositionVariance, aa),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_aa_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PositionVariance, bb),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_bb_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bb"
		},
};
static ber_tlv_tag_t asn_DEF_PositionVariance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PositionVariance_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* aa at 141 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* bb at 142 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PositionVariance_specs_1 = {
	sizeof(struct PositionVariance),
	offsetof(struct PositionVariance, _asn_ctx),
	asn_MAP_PositionVariance_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PositionVariance = {
	"PositionVariance",
	"PositionVariance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PositionVariance_tags_1,
	sizeof(asn_DEF_PositionVariance_tags_1)
		/sizeof(asn_DEF_PositionVariance_tags_1[0]), /* 1 */
	asn_DEF_PositionVariance_tags_1,	/* Same as above */
	sizeof(asn_DEF_PositionVariance_tags_1)
		/sizeof(asn_DEF_PositionVariance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PositionVariance_1,
	2,	/* Elements count */
	&asn_SPC_PositionVariance_specs_1	/* Additional specs */
};

