/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_PositionVariance_H_
#define	_PositionVariance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionVariance */
typedef struct PositionVariance {
	long	 aa;
	long	 bb;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionVariance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionVariance;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionVariance_H_ */
