/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_VehicleDescription_H_
#define	_VehicleDescription_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleDescription {
	VehicleDescription_unknown	= 0,
	VehicleDescription_car	= 1,
	VehicleDescription_lightGoodsVehicle	= 2,
	VehicleDescription_heavyGoodsVehicle	= 3,
	VehicleDescription_publicTransportVehicle	= 4,
	VehicleDescription_pedalCycle	= 5,
	VehicleDescription_emergencyVehicle	= 6,
	VehicleDescription_worksVehicle	= 7,
	VehicleDescription_exceptionalSizeVehicle	= 8,
	VehicleDescription_vehicleWithTrailer	= 9,
	VehicleDescription_highSidedVehicle	= 10,
	VehicleDescription_minibus	= 11,
	VehicleDescription_taxi	= 12,
	VehicleDescription_tram	= 13,
	VehicleDescription_trolleyBus	= 14,
	VehicleDescription_train	= 15,
	VehicleDescription_postBus	= 16,
	VehicleDescription_schoolBus	= 17,
	VehicleDescription_militaryVvehicle	= 18,
	VehicleDescription_motorcycle	= 19,
	VehicleDescription_sledge	= 20,
	VehicleDescription_assistanceVehicle	= 21,
	VehicleDescription_vehicle	= 31
} e_VehicleDescription;

/* VehicleDescription */
typedef long	 VehicleDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleDescription;
asn_struct_free_f VehicleDescription_free;
asn_struct_print_f VehicleDescription_print;
asn_constr_check_f VehicleDescription_constraint;
ber_type_decoder_f VehicleDescription_decode_ber;
der_type_encoder_f VehicleDescription_encode_der;
xer_type_decoder_f VehicleDescription_decode_xer;
xer_type_encoder_f VehicleDescription_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleDescription_H_ */
