/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_VehicleAttribute_H_
#define	_VehicleAttribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleAttribute {
	VehicleAttribute_safespot	= 0,
	VehicleAttribute_safeprobe	= 1,
	VehicleAttribute_cvis	= 2,
	VehicleAttribute_crashed	= 3
} e_VehicleAttribute;

/* VehicleAttribute */
typedef BIT_STRING_t	 VehicleAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleAttribute;
asn_struct_free_f VehicleAttribute_free;
asn_struct_print_f VehicleAttribute_print;
asn_constr_check_f VehicleAttribute_constraint;
ber_type_decoder_f VehicleAttribute_decode_ber;
der_type_encoder_f VehicleAttribute_encode_der;
xer_type_decoder_f VehicleAttribute_decode_xer;
xer_type_encoder_f VehicleAttribute_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleAttribute_H_ */
