/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Interoperability"
 * 	found in "interoperability.asn"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_VisibilityRange_H_
#define	_VisibilityRange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VisibilityRange */
typedef long	 VisibilityRange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VisibilityRange;
asn_struct_free_f VisibilityRange_free;
asn_struct_print_f VisibilityRange_print;
asn_constr_check_f VisibilityRange_constraint;
ber_type_decoder_f VisibilityRange_decode_ber;
der_type_encoder_f VisibilityRange_encode_der;
xer_type_decoder_f VisibilityRange_decode_xer;
xer_type_encoder_f VisibilityRange_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VisibilityRange_H_ */
