/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_EmptyRequest_H_
#define	_EmptyRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EmptyRequest */
typedef struct EmptyRequest {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EmptyRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EmptyRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _EmptyRequest_H_ */
