/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_PublishRequest_H_
#define	_PublishRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ByteString.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PublishRequest */
typedef struct PublishRequest {
	ByteString_t	 data;
	long	 interval;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublishRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublishRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _PublishRequest_H_ */
