/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include <asn_internal.h>

#include "ReplyMessage.h"

static int
memb_serial_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_payload_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage__payload, choice.openack),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenReply,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"openack"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage__payload, choice.closeack),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CloseReply,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"closeack"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage__payload, choice.msg),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgReply,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage__payload, choice.service),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgReply,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"service"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage__payload, choice.fault),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FaultReply,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fault"
		},
};
static asn_TYPE_tag2member_t asn_MAP_payload_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* openack at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* closeack at 26 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* msg at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* service at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* fault at 30 */
};
static asn_CHOICE_specifics_t asn_SPC_payload_specs_3 = {
	sizeof(struct ReplyMessage__payload),
	offsetof(struct ReplyMessage__payload, _asn_ctx),
	offsetof(struct ReplyMessage__payload, present),
	sizeof(((struct ReplyMessage__payload *)0)->present),
	asn_MAP_payload_tag2el_3,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_payload_3 = {
	"payload",
	"payload",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_payload_3,
	5,	/* Elements count */
	&asn_SPC_payload_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ReplyMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage, serial),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_serial_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReplyMessage, payload),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_payload_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"payload"
		},
};
static ber_tlv_tag_t asn_DEF_ReplyMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReplyMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* serial at 23 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* openack at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* closeack at 26 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* msg at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* service at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 } /* fault at 30 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReplyMessage_specs_1 = {
	sizeof(struct ReplyMessage),
	offsetof(struct ReplyMessage, _asn_ctx),
	asn_MAP_ReplyMessage_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReplyMessage = {
	"ReplyMessage",
	"ReplyMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReplyMessage_tags_1,
	sizeof(asn_DEF_ReplyMessage_tags_1)
		/sizeof(asn_DEF_ReplyMessage_tags_1[0]), /* 1 */
	asn_DEF_ReplyMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReplyMessage_tags_1)
		/sizeof(asn_DEF_ReplyMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReplyMessage_1,
	2,	/* Elements count */
	&asn_SPC_ReplyMessage_specs_1	/* Additional specs */
};

