/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CalmFast"
 * 	found in "calmfast.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_UrlString_H_
#define	_UrlString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UrlString */
typedef OCTET_STRING_t	 UrlString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UrlString;
asn_struct_free_f UrlString_free;
asn_struct_print_f UrlString_print;
asn_constr_check_f UrlString_constraint;
ber_type_decoder_f UrlString_decode_ber;
der_type_encoder_f UrlString_encode_der;
xer_type_decoder_f UrlString_decode_xer;
xer_type_encoder_f UrlString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UrlString_H_ */
