/*
 * $Id: ServiceChannel.c $
 *
 * This file is part of the CALM FAST Message Library.
 * 
 * Author: Andras Takacs <andras.takacs@ramsys.hu>
 *
 * Copyright 2006-2009 Ramsys Zrt
 *
 * CALM FAST Message Library is free software; you can redistribute
 * it and/or modify it under the terms of the GNU LEsser General Public
 * License as published by the Free Software Foundation; version 3 of
 * the License.
 *
 * CALM FAST Message Library is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with CALM FAST Message Library; if not, write to the Free
 * Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 * 02111-1307 USA.
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CALMime"
 * 	found in "29281.asn"
 * 	`asn1c -fnative-types -fcompound-names -fskeletons-copy`
 */

#include <asn_internal.h>

#include "ServiceChannel.h"

static int
__LIBFAST__memb_serviceChannel_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_serviceChannel_constr_2 = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ServiceChannel_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceChannel, serviceChannel),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		__LIBFAST__memb_serviceChannel_constraint_1,
		&asn_PER_memb_serviceChannel_constr_2,
		0,
		"serviceChannel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceChannel, medium),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_MedType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"medium"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceChannel, schParams),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"schParams"
		},
};
static ber_tlv_tag_t asn_DEF_ServiceChannel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ServiceChannel_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* serviceChannel at 56 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* schParams at 58 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 } /* medium at 57 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServiceChannel_specs_1 = {
	sizeof(struct ServiceChannel),
	offsetof(struct ServiceChannel, _asn_ctx),
	asn_MAP_ServiceChannel_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServiceChannel = {
	"ServiceChannel",
	"ServiceChannel",
	__LIBFAST__SEQUENCE_free,
	__LIBFAST__SEQUENCE_print,
	__LIBFAST__SEQUENCE_constraint,
	__LIBFAST__SEQUENCE_decode_ber,
	__LIBFAST__SEQUENCE_encode_der,
	__LIBFAST__SEQUENCE_decode_xer,
	__LIBFAST__SEQUENCE_encode_xer,
	__LIBFAST__SEQUENCE_decode_uper,
	__LIBFAST__SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServiceChannel_tags_1,
	sizeof(asn_DEF_ServiceChannel_tags_1)
		/sizeof(asn_DEF_ServiceChannel_tags_1[0]), /* 1 */
	asn_DEF_ServiceChannel_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceChannel_tags_1)
		/sizeof(asn_DEF_ServiceChannel_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ServiceChannel_1,
	3,	/* Elements count */
	&asn_SPC_ServiceChannel_specs_1	/* Additional specs */
};

